//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Ohana3DS.My
{

    //OBSERVAÇÃO: o arquivo é gerado automaticamente. Não o modifique diretamente. Para fazer alterações,
    // ou se você encontrar erros de compilação neste arquivo, vá para o Designer de Projeto
    // (vá para Propriedades do Projeto ou clique duas vezes no nó Meu Projeto em
    // Gerenciador de Soluções) e faça as alterações na guia Aplicativo.
    //
    internal partial class MyApplication
	{

		[System.Diagnostics.DebuggerStepThroughAttribute()]
		public MyApplication() : base(global::Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
		{
			this.IsSingleInstance = false;
			this.EnableVisualStyles = true;
			this.SaveMySettingsOnExit = true;
			this.ShutdownStyle = global::Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses;
		}

		[System.Diagnostics.DebuggerStepThroughAttribute()]
		protected override void OnCreateMainForm()
		{
			this.MainForm = My.MyProject.Forms.FrmMain;
		}
	}
}
